### PR TITLE
Fix filesystem inodes metrics for Stackdriver

### PR DESCRIPTION
**Pull request by wangzhen127**
**What this PR does**

This PR fixes the volume inodes metrics according to recent Stackdriver review.

### CODE REVIEW

**Comment by wangzhen127** [comment]
Ping :)

**Comment by dashpole** [comment]
this isn't for volumes, right?

**Comment by wangzhen127** [comment]
Right. It is for FS. I used volume as the previous used volume (which should be FS, too). Updated the commit message and PR title.

**Comment by wangzhen127** [comment]
Ping @bmoyles0117 :)

**Comment by bmoyles0117** [comment]
Have you attempted to run these changes in a container image to ensure that the metrics are being propagated correctly?

**Comment by wangzhen127** [comment]
> Have you attempted to run these changes in a container image to ensure that the metrics are being propagated correctly?

Not yet. Is there any doc on that?

**Comment by wangzhen127** [comment]
I have manually tested this change and I can see the metrics.

**Review by bmoyles0117 — APPROVED** [review]

**Comment by wangzhen127** [comment]
Will this PR be merged automatically? I didn't see a submit button.

**Comment by bmoyles0117** [comment]
@x13n can you be the final approver/merger on this one?

**Review by x13n — APPROVED** [review]
Yup, LGTM.

**Pull request merged**
